name: 'Create Release Pull Request'

on:
  push:
    branches:
      - releases/*

jobs:
  build:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request content
        id: create-pr-content
        run: |
          echo "::set-output name=pr-title::$(./script/draft-release/release-pr-content.sh title ${GITHUB_REF#refs/heads/})\n"
          echo "::set-output name=pr-body::$(./script/draft-release/release-pr-content.sh body ${GITHUB_REF#refs/heads/})\n"

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_PRS_APP_ID }}
          private_key: ${{ secrets.RELEASE_PRS_APP_PRIVATE_KEY }}

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: ${{ steps.create-pr-content.outputs.pr-title }}
          body: ${{ steps.create-pr-content.outputs.pr-body }}
          branch: ${{ github.ref }}
          base: development
