name: 'Release Pull Request'

on:
  push:
    branches:
      - releases/*

jobs:
  build:
    #name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Pull Request content
        id: create_pr_content
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          VERSION=$(echo ${BRANCH_NAME#releases/})
          RELEASE_DESCRIPTION="v${VERSION} production release"
          if [[ "$VERSION" == *"-"* ]]; then
            BUILD_TYPE_AND_NUMBER=$(echo ${VERSION##*-})
            if [[ "$BUILD_TYPE_AND_NUMBER" != *"beta" ]]; then
              echo "Only beta and production builds have release PRs"
            fi
            BUILD_TYPE="beta"
            BUILD_NUMBER=$(echo ${BUILD_TYPE_AND_NUMBER:4})
            RELEASE_DESCRIPTION="${BUILD_NUMBER}th beta of the v${VERSION} series"
          fi

          TITLE="Release $VERSION"
          BODY="## Description
Looking for the PR for the upcoming ${RELEASE_DESCRIPTION}? Well, you've just found it, congratulations!

## Release checklist

- [ ] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [ ] Verify that all feature flags are flipped appropriately
- [ ] If there are any new metrics, ensure that central and desktop.github.com have been updated
"

          echo "::set-output name=pr_title::$TITLE"
          echo "::set-output name=pr_body::$BODY"

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_pr_content.outputs.pr_title }}
          body: ${{ steps.create_pr_content.outputs.pr_body }}
          branch: ${{ github.ref }}
          base: development
