name: 'Create Release Pull Request'

on:
  push:
    branches:
      - releases/*

jobs:
  build:
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Pull Request content
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          VERSION=$(echo ${BRANCH_NAME#releases/})
          RELEASE_DESCRIPTION="v${VERSION} production release"
          if [[ "$VERSION" == *"-"* ]]; then
            BUILD_TYPE_AND_NUMBER=$(echo ${VERSION##*-})
            if [[ "$BUILD_TYPE_AND_NUMBER" != *"beta" ]]; then
              echo "Only beta and production builds have release PRs"
            fi
            BUILD_TYPE="beta"
            BUILD_NUMBER=$(echo ${BUILD_TYPE_AND_NUMBER:4})
            RELEASE_DESCRIPTION="${BUILD_NUMBER}th beta of the v${VERSION} series"
          fi

          PR_TITLE="Release $VERSION"
          PR_BODY=$(cat << EOF
          ## Description
          Looking for the PR for the upcoming ${RELEASE_DESCRIPTION}? Well, you've just found it, congratulations!

          ## Release checklist

          - [ ] Check to see if there are any errors in Sentry that have only occurred since the last production release
          - [ ] Verify that all feature flags are flipped appropriately
          - [ ] If there are any new metrics, ensure that central and desktop.github.com have been updated
          EOF
          )

          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "PR_TITLE<<EOF" >> $GITHUB_ENV
          echo "$PR_TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ secrets.RELEASE_PR_APP_TOKEN }}
          title: ${{ env.PR_TITLE }}
          body: ${{ env.PR_BODY }}
          branch: ${{ github.ref }}
          base: development
